name: Deploy Next.js on EC2

on:
  push:
    branches:
      - main
      - stage

jobs:
  deploy:
    name: Deploy on EC2
    runs-on: self-hosted

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: ${{ github.ref_name }}-app # Clone the repo into the branch-specific path

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up environment variables for main or stage
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "Setting up .env for main branch"
            echo "JWT_SECRET_KEY=${{ secrets.MAIN_JWT_SECRET_KEY }}" > .env
            echo "MONGODB_URI=${{ secrets.MAIN_MONGODB_URI }}" >> .env
          elif [ "${{ github.ref_name }}" == "stage" ]; then
            echo "Setting up .env for stage branch"
            echo "JWT_SECRET_KEY=${{ secrets.STAGE_JWT_SECRET_KEY }}" > .env
            echo "MONGODB_URI=${{ secrets.STAGE_MONGODB_URI }}" >> .env
          fi
        shell: bash
        working-directory: ${{ github.ref_name }}-app

      - name: Install dependencies
        run: yarn install
        working-directory: ${{ github.ref_name }}-app

      - name: Build Next.js app
        run: yarn build
        working-directory: ${{ github.ref_name }}-app

      - name: Install production dependencies and start the app
        run: |
          # Define unique paths for each branch
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            pm2 restart bitelink-main
          elif [ "${{ github.ref }}" == "refs/heads/stage" ]; then
            pm2 restart bitelink-stage
          fi